check

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -167,59 +167,59 @@ runs:
     #     sed -i "s/sonar_scan=x/sonar_scan=${icon}/g" $RUNNER_TEMP/icons.properties
 
     # Citadel section
-    - name: Prepare citadel Json file
-      if: ${{ env.TRIGGER_CITADEL_SCAN }}
-      shell: bash
-      run: |
-        # pip3 install pyyaml==6.0.1
+    # - name: Prepare citadel Json file
+    #   if: ${{ env.TRIGGER_CITADEL_SCAN }}
+    #   shell: bash
+    #   run: |
+    #     # pip3 install pyyaml==6.0.1
 
-        python3 ${GITHUB_ACTION_PATH}/citadel/citadel.py \
-          "${GITHUB_WORKSPACE}/citadel-config.yaml" "${{ env.PROJECT_PATH }}" "$GITHUB_WORKFLOW_REF" "$RUNNER_TEMP"
+    #     python3 ${GITHUB_ACTION_PATH}/citadel/citadel.py \
+    #       "${GITHUB_WORKSPACE}/citadel-config.yaml" "${{ env.PROJECT_PATH }}" "$GITHUB_WORKFLOW_REF" "$RUNNER_TEMP"
         
-        echo "CITADEL_JSON_PATH=$RUNNER_TEMP/citadel.json" >> $GITHUB_ENV
+    #     echo "CITADEL_JSON_PATH=$RUNNER_TEMP/citadel.json" >> $GITHUB_ENV
 
-    - name: Upload to the citadel host
-      if: ${{ env.CITADEL_JSON_PATH }}
-      id: citadel-scan 
-      shell: bash
-      run: |        
-        file_paths="${{ env.CITADEL_JSON_PATH }}"
-        # unset CITADEL_JSON_PATH so that it doesn't get trigger again by other steps
-        echo "CITADEL_JSON_PATH=" >> $GITHUB_ENV
-        IFS=', ' read -ra file_paths_array <<< "$file_paths"
-        for file_path in "${file_paths_array[@]}"; do 
-          echo "Processing File $file_path"
-          cat $file_path
-          curl -vvvX POST '${{ env.CITADEL_URL }}' --silent --fail --show-error -d @$file_path -H 'Content-Type: application/json' -H "Connection: close"  
-          sleep ${{ env.CITADEL_JSON_LIST_SLEEP_SECONDS || 60  }}   # If env not passed, Sleeping for 60 seconds (default)
-        done
+    # - name: Upload to the citadel host
+    #   if: ${{ env.CITADEL_JSON_PATH }}
+    #   id: citadel-scan 
+    #   shell: bash
+    #   run: |        
+    #     file_paths="${{ env.CITADEL_JSON_PATH }}"
+    #     # unset CITADEL_JSON_PATH so that it doesn't get trigger again by other steps
+    #     echo "CITADEL_JSON_PATH=" >> $GITHUB_ENV
+    #     IFS=', ' read -ra file_paths_array <<< "$file_paths"
+    #     for file_path in "${file_paths_array[@]}"; do 
+    #       echo "Processing File $file_path"
+    #       cat $file_path
+    #       curl -vvvX POST '${{ env.CITADEL_URL }}' --silent --fail --show-error -d @$file_path -H 'Content-Type: application/json' -H "Connection: close"  
+    #       sleep ${{ env.CITADEL_JSON_LIST_SLEEP_SECONDS || 60  }}   # If env not passed, Sleeping for 60 seconds (default)
+    #     done
 
-    - name: Citadel scan tracking    
-      shell: bash
-      if: ${{ always() && env.TRIGGER_CITADEL_SCAN }}
-      run: |
-        icon="boom"
-        [[ "${{ steps.citadel-scan.outcome }}" == "success" ]] && icon="white_check_mark"
+    # - name: Citadel scan tracking    
+    #   shell: bash
+    #   if: ${{ always() && env.TRIGGER_CITADEL_SCAN }}
+    #   run: |
+    #     icon="boom"
+    #     [[ "${{ steps.citadel-scan.outcome }}" == "success" ]] && icon="white_check_mark"
 
-        sed -i "s/citadel_scan=x/citadel_scan=${icon}/g" $RUNNER_TEMP/icons.properties
+    #     sed -i "s/citadel_scan=x/citadel_scan=${icon}/g" $RUNNER_TEMP/icons.properties
         
-    # Blackduck section
-    - name: Blackduck Scan
-      if: ${{ env.BlackDuck_Project_Name }}
-      id: blackduck-scan
-      uses: addnab/docker-run-action@v3
-      with:
-        image: docker.repo.orl.eng.hitachivantara.com/blackducksoftware/detect:9
-        options: --entrypoint "/bin/bash" -v ${{ github.workspace }}:/workdir
-        run: |
-          java -jar /synopsys-detect.jar \
-           --detect.source.path=${{ env.BlackDuck_Source_Path || '/workdir' }} \
-           --detect.project.version.name="${{ env.BlackDuck_Project_Version }}" \
-           --detect.project.name="${{ env.BlackDuck_Project_Name }}" \
-           --detect.accuracy.required=NONE \
-           --blackduck.api.token="${{ env.BlackDuck_Api_Token }}" \
-           --blackduck.url="${{ env.BlackDuck_Url }}" \
-           --detect.blackduck.signature.scanner.snippet.matching="NONE" ${{ env.ADDITIONAL_ARGS }}
+    # # Blackduck section
+    # - name: Blackduck Scan
+    #   if: ${{ env.BlackDuck_Project_Name }}
+    #   id: blackduck-scan
+    #   uses: addnab/docker-run-action@v3
+    #   with:
+    #     image: docker.repo.orl.eng.hitachivantara.com/blackducksoftware/detect:9
+    #     options: --entrypoint "/bin/bash" -v ${{ github.workspace }}:/workdir
+    #     run: |
+    #       java -jar /synopsys-detect.jar \
+    #        --detect.source.path=${{ env.BlackDuck_Source_Path || '/workdir' }} \
+    #        --detect.project.version.name="${{ env.BlackDuck_Project_Version }}" \
+    #        --detect.project.name="${{ env.BlackDuck_Project_Name }}" \
+    #        --detect.accuracy.required=NONE \
+    #        --blackduck.api.token="${{ env.BlackDuck_Api_Token }}" \
+    #        --blackduck.url="${{ env.BlackDuck_Url }}" \
+    #        --detect.blackduck.signature.scanner.snippet.matching="NONE" ${{ env.ADDITIONAL_ARGS }}
 
     # - name: Blackduck scan tracking
     #   shell: bash
@@ -246,95 +246,95 @@ runs:
     #       --enableRetired
 
     # Tagging
-    - name: Prepare tagging
-      if: ${{ env.Tag_version }}
-      id: prepare-tagging
-      shell: bash
-      run: |
-        push="true"
-        if [ "${{ env.push_tag_only }}" == "true" ]; then
-          push="origin ${{ env.Tag_version }} -f"
-        fi
+    # - name: Prepare tagging
+    #   if: ${{ env.Tag_version }}
+    #   id: prepare-tagging
+    #   shell: bash
+    #   run: |
+    #     push="true"
+    #     if [ "${{ env.push_tag_only }}" == "true" ]; then
+    #       push="origin ${{ env.Tag_version }} -f"
+    #     fi
         
-        echo "push=${push}" >> $GITHUB_OUTPUT
+    #     echo "push=${push}" >> $GITHUB_OUTPUT
 
-    - name: Create Tag
-      if: ${{ env.Tag_version }}
-      id: git-tag
-      uses: EndBug/add-and-commit@v9
-      with:
-        add: '.'
-        commit: --signoff
-        default_author: github_actions
-        message: '[CI/CD] - :robot: Changes captured in the ${{ env.Tag_version }} tag'
-        tag: '${{ env.Tag_version }}'
-        tag_push: '--force'
-        pull: '--rebase --autostash'
-        push: ${{ steps.prepare-tagging.outputs.push || true }}
+    # - name: Create Tag
+    #   if: ${{ env.Tag_version }}
+    #   id: git-tag
+    #   uses: EndBug/add-and-commit@v9
+    #   with:
+    #     add: '.'
+    #     commit: --signoff
+    #     default_author: github_actions
+    #     message: '[CI/CD] - :robot: Changes captured in the ${{ env.Tag_version }} tag'
+    #     tag: '${{ env.Tag_version }}'
+    #     tag_push: '--force'
+    #     pull: '--rebase --autostash'
+    #     push: ${{ steps.prepare-tagging.outputs.push || true }}
 
-    - name: Create tag tracking
-      shell: bash
-      if: ${{ always() && env.Tag_version }}
-      run: |
-        icon="boom"
-        [[ "${{ steps.git-tag.outcome }}" == "success" ]] && icon="white_check_mark"
+    # - name: Create tag tracking
+    #   shell: bash
+    #   if: ${{ always() && env.Tag_version }}
+    #   run: |
+    #     icon="boom"
+    #     [[ "${{ steps.git-tag.outcome }}" == "success" ]] && icon="white_check_mark"
 
-        sed -i "s/create_tag=x/create_tag=${icon}/g" $RUNNER_TEMP/icons.properties
+    #     sed -i "s/create_tag=x/create_tag=${icon}/g" $RUNNER_TEMP/icons.properties
 
-    - name: Publish Artifacts to Registry
-      if: ${{ env.artifacts_manifest_file }}
-      continue-on-error: false
-      uses: lumada-common-services/registry-publication@v1.1.1
-      with:
-        ARTIFACTS_CONFIG_FILE: ${{ env.artifacts_manifest_file }}
-        ARTIFACTORY_APIKEY: ${{ env.artifactory_api_key }}
-        ARTIFACTORY_USER: ${{ env.artifactory_user }}
-        BUILD_NUMBER: ${{ env.run_number }}
-        BUILD_NAME: ${{ env.job }}
-        BUILD_VERSION: ${{ env.pkg_version }}
-        WORKSPACE: ${{ env.workspace }}
-        BUILD_URL: ${{ env.build_url }}
+    # - name: Publish Artifacts to Registry
+    #   if: ${{ env.artifacts_manifest_file }}
+    #   continue-on-error: false
+    #   uses: lumada-common-services/registry-publication@v1.1.1
+    #   with:
+    #     ARTIFACTS_CONFIG_FILE: ${{ env.artifacts_manifest_file }}
+    #     ARTIFACTORY_APIKEY: ${{ env.artifactory_api_key }}
+    #     ARTIFACTORY_USER: ${{ env.artifactory_user }}
+    #     BUILD_NUMBER: ${{ env.run_number }}
+    #     BUILD_NAME: ${{ env.job }}
+    #     BUILD_VERSION: ${{ env.pkg_version }}
+    #     WORKSPACE: ${{ env.workspace }}
+    #     BUILD_URL: ${{ env.build_url }}
 
-    - name: Create and Update frogbot config file
-      if: ${{ env.JF_CHANGED_PATHS && env.JF_URL }}
-      run: |   
-        python3 ${GITHUB_ACTION_PATH}/frogbot/frogbot.py "${{ env.JF_CHANGED_PATHS }}" "${GITHUB_WORKSPACE}" "${{ github.event.repository.name }}" "${{ github.head_ref }}"  
-        cat .frogbot/frogbot-config.yml
-      shell: bash  
-    
-    # - name: File
+    # - name: Create and Update frogbot config file
     #   if: ${{ env.JF_CHANGED_PATHS && env.JF_URL }}
-    #   run: ls -alR
+    #   run: |   
+    #     python3 ${GITHUB_ACTION_PATH}/frogbot/frogbot.py "${{ env.JF_CHANGED_PATHS }}" "${GITHUB_WORKSPACE}" "${{ github.event.repository.name }}" "${{ github.head_ref }}"  
+    #     cat .frogbot/frogbot-config.yml
     #   shell: bash  
     
-    - name: FrogBot
-      if: ${{ env.JF_URL }}    
-      uses: jfrog/frogbot@v2
-      env:
-        JF_URL: ${{ env.JF_URL }}
-        JF_ACCESS_TOKEN: ${{ env.JF_ACCESS_TOKEN }}
-        JF_GIT_TOKEN: ${{ env.JF_GIT_TOKEN }}
-        JF_WORKING_DIR: ${{ env.JF_WORKING_DIR }}
-        JF_FAIL: "FALSE"
-      with:
-        version: 2.17.1 
-
-    - name: Creating Kind Cluster 
-      id: cluster-creation
-      if: ${{env.KIND_CLUSTER_NAME && env.KIND_CLUSTER_ACTION == 'CREATE' }}
-      run: |
-        docker exec -i kind-container kind create cluster --name ${{ env.KIND_CLUSTER_NAME }} --config /mnt/${{env.CONFIG_FILE_NAME}}                              # Creating kind cluster inside of kind-container where Configuration file is at root level 
-        docker exec -i kind-container kind export kubeconfig --name ${{ env.KIND_CLUSTER_NAME }} --kubeconfig /mnt/kubeconfig                                      # Exporting kubeconfig file to /mnt folder mapped to github workspace
-        docker exec -i kind-container kind get clusters
-        docker network connect kind bootstrap-image                                                                                                                # Connecting Bootstrap image to kind network                        
-        kubectl config set-cluster kind-${{ env.KIND_CLUSTER_NAME }} --server=https://${{ env.KIND_CLUSTER_NAME }}-control-plane:6443 --kubeconfig=./kubeconfig
-      shell: bash
+    # # - name: File
+    # #   if: ${{ env.JF_CHANGED_PATHS && env.JF_URL }}
+    # #   run: ls -alR
+    # #   shell: bash  
     
-    - name: Deleting Kind Cluster
-      id: cluster-deletion
-      if: ${{env.KIND_CLUSTER_NAME && env.KIND_CLUSTER_ACTION == 'DELETE' }}
-      run : docker exec -i kind-container kind delete cluster --name ${{ env.KIND_CLUSTER_NAME }} 
-      shell: bash
+    # - name: FrogBot
+    #   if: ${{ env.JF_URL }}    
+    #   uses: jfrog/frogbot@v2
+    #   env:
+    #     JF_URL: ${{ env.JF_URL }}
+    #     JF_ACCESS_TOKEN: ${{ env.JF_ACCESS_TOKEN }}
+    #     JF_GIT_TOKEN: ${{ env.JF_GIT_TOKEN }}
+    #     JF_WORKING_DIR: ${{ env.JF_WORKING_DIR }}
+    #     JF_FAIL: "FALSE"
+    #   with:
+    #     version: 2.17.1 
+
+    # - name: Creating Kind Cluster 
+    #   id: cluster-creation
+    #   if: ${{env.KIND_CLUSTER_NAME && env.KIND_CLUSTER_ACTION == 'CREATE' }}
+    #   run: |
+    #     docker exec -i kind-container kind create cluster --name ${{ env.KIND_CLUSTER_NAME }} --config /mnt/${{env.CONFIG_FILE_NAME}}                              # Creating kind cluster inside of kind-container where Configuration file is at root level 
+    #     docker exec -i kind-container kind export kubeconfig --name ${{ env.KIND_CLUSTER_NAME }} --kubeconfig /mnt/kubeconfig                                      # Exporting kubeconfig file to /mnt folder mapped to github workspace
+    #     docker exec -i kind-container kind get clusters
+    #     docker network connect kind bootstrap-image                                                                                                                # Connecting Bootstrap image to kind network                        
+    #     kubectl config set-cluster kind-${{ env.KIND_CLUSTER_NAME }} --server=https://${{ env.KIND_CLUSTER_NAME }}-control-plane:6443 --kubeconfig=./kubeconfig
+    #   shell: bash
+    
+    # - name: Deleting Kind Cluster
+    #   id: cluster-deletion
+    #   if: ${{env.KIND_CLUSTER_NAME && env.KIND_CLUSTER_ACTION == 'DELETE' }}
+    #   run : docker exec -i kind-container kind delete cluster --name ${{ env.KIND_CLUSTER_NAME }} 
+    #   shell: bash
 
     - name: Read icon properties
       if: ${{ env.report }}
